#!/bin/bash
zip -r newversion.zip start.m stop.m include/ versionchanges Version.html
scp newversion.zip sidash.de:/html/ETS/
scp update.m sidash.de:/html/ETS
scp version sidash.de:/html/ETS
scp Version.html sidash.de:/html/ETS/index.html
rm ./*.zip
