#!/bin/bash
zip -r newversion.zip start.m include/ Version.html versionchanges
scp newversion.zip sidash.de:/html/ETS/
scp update.m sidash.de:/html/ETS
scp version sidash.de:/html/ETS
scp Version.html sidash.de:/html/ETS/index.html
rm ./*.zip
